// Turns src/abi/Game.json (written by `npm run export-abi` in backend/) into a typed
// `as const` module so wagmi/viem infer function names, args and return types.
// Runs automatically before `dev` and `build`; run `npm run abi` after exporting a new ABI.
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const source = path.join(root, 'src/abi/Game.json')
const target = path.join(root, 'src/abi/gameAbi.ts')

const json = JSON.parse(readFileSync(source, 'utf8'))
const abi = Array.isArray(json) ? json : json.abi
if (!Array.isArray(abi)) throw new Error(`${source} is neither an ABI array nor an artifact with .abi`)

const output = `// Generated by scripts/generate-abi.mjs from Game.json. Do not edit by hand.
export const gameAbi = ${JSON.stringify(abi, null, 2)} as const
`

let current = ''
try {
  current = readFileSync(target, 'utf8')
} catch {
  // first run
}
if (current !== output) {
  writeFileSync(target, output)
  console.log(`generate-abi: wrote ${abi.length} entries to src/abi/gameAbi.ts`)
}
